timeout: 2

/UnstableOS
	protocol: multiboot
	path: boot():/UnstableOS.bin
	module_path: boot():/memdisk.tar

/UnstableOS VGA-only
	protocol: multiboot
	path: boot():/UnstableOS.bin
	module_path: boot():/memdisk.tar
	cmdline: vga