#ifndef ARGS_H
#define ARGS_H

enum redir_types {
    REDIR_END,
    REDIR_FD_FD, // do dup2 on existing fds
    REDIR_FD_FILE // do dup2 on now open fd_r, close after
};
struct redirection {
    enum redir_types redir_type;
    int fd_l;
    int fd_r; // -1 means delete
};

enum token_types {
    TOKEN_END,
    TOKEN_EMPTY, // when we need to consume a token
    TOKEN_STRING,
    TOKEN_PIPE,
    TOKEN_REDIR_IN_FD, // <&1, cannot have space between < and &
    TOKEN_REDIR_OUT_FD,

    // doesn't make much sense, instead of opening as O_APPEND,
    // we lseek(fd, 0, SEEK_END)
    TOKEN_REDIR_OUT_APPEND_FD,
    TOKEN_REDIR_IN,
    TOKEN_REDIR_OUT,
    TOKEN_REDIR_OUT_APPEND,
    TOKEN_REDIR_INOUT,
};
struct token {
    enum token_types type;
    char * string;

    // 1 if this token got generated by running into a whitespace
    // that is - deliminated by a whitespace on the right side
    // 0 otherwise (like breaking up the token with *s = '\0'
    char is_whitespaced;
};

// destroys the input buffer!
// call free on returned buffer on end
struct token * tokenize_buffer(char * buffer);

char * const** extract_args(struct token * tokens, struct redirection *** redir_out);

#endif