#ifndef KEYBOARD_H
#define KEYBOARD_H

#include "keyboard.h"

#define PS2_DATA_PORT 0x60
#define PS2_COMM_PORT 0x64


#define PS2_KEY_MOD_NUMLOCK_MASK (KEY_MOD_NUMLOCK_MASK >> 12)
#define PS2_KEY_MOD_CAPSLOCK_MASK (KEY_MOD_CAPSLOCK_MASK >> 12)
#define PS2_KEY_MOD_LSHIFT_MASK (KEY_MOD_LSHIFT_MASK >> 12)
#define PS2_KEY_MOD_RSHIFT_MASK (KEY_MOD_RSHIFT_MASK >> 12)
#define PS2_KEY_MOD_LCONTROL_MASK (KEY_MOD_LCONTROL_MASK >> 12)
#define PS2_KEY_MOD_RCONTROL_MASK (KEY_MOD_RCONTROL_MASK >> 12)
#define PS2_KEY_MOD_LALT_MASK (KEY_MOD_LALT_MASK >> 12)
#define PS2_KEY_MOD_RALT_MASK (KEY_MOD_RALT_MASK >> 12)
#define PS2_KEY_MOD_LMETA_MASK (KEY_MOD_LMETA_MASK >> 12)
#define PS2_KEY_MOD_RMETA_MASK (KEY_MOD_RMETA_MASK >> 12)

enum ps2_device_types {
    PS2_DEVICE_STD_MOUSE,
    PS2_DEVICE_MOUSE_SCROLL = 0x03,
    PS2_DEVICE_5_BUTTON_MOUSE,
    PS2_DEVICE_KEYBOARD = 0xAB,
    PS2_DEVICE_NCD_SUN_KEYBOARD,

    PS2_DEVICE_UNSPECIFIED = 0xFF 
};

enum ps2_keyboard_types {
    PS2_DEVICE_KEYBOARD_MF2_1 = 0x83,
    PS2_DEVICE_KEYBOARD_MF2_2 = 0x41, // translated
    PS2_DEVICE_KEYBOARD_MF2_3 = 0xC1,
    PS2_DEVICE_SHORT = 0x84,
    PS2_DEVICE_SHORT_2 = 0x54, // translated
    PS2_DEVICE_KEYBOARD_NCD_N97 = 0x85,
    PS2_DEVICE_KEYBOARD_122_KEY_HCK = 0x85, // host connect(ed) keyboard
    PS2_DEVICE_KEYBOARD_122_KEY,
    PS2_DEVICE_KEYBOARD_JAPAN_G = 0x90,
    PS2_DEVICE_KEYBOARD_JAPAN_P,
    PS2_DEVICE_KEYBOARD_JAPAN_A,
    PS2_DEVICE_KEYBOARD_NCD_SUN_LAY = 0xA1,
};

enum ps2_controller_port_test_response {
    PS2_CONTROLLER_TEST_PASSED,
    PS2_CONTROLLER_TEST_CLK_LINE_LOW, // stuck at low
    PS2_CONTROLLER_TEST_CLK_LINE_HIGH,
    PS2_CONTROLLER_TEST_DATA_LINE_LOW,
    PS2_CONTROLLER_TEST_DATA_LINE_HIGH,
};
#define PS2_CONTROLLER_SELF_TEST_PASSED 0x55
#define PS2_CONTROLLER_SELF_TEST_FAILED 0xFC

enum ps2_controller_config_byte {
    PS2_CONTROLLER_CONFIG_ENABLE_PORT1_INTERRUPT = 1, // 1 = enabled
    PS2_CONTROLLER_CONFIG_ENABLE_PORT2_INTERRUPT = 2,
    PS2_CONTROLLER_CONFIG_PASED_POST = 4, // 1 = passed post, 0 = didn't in which case, how did we get here?
    PS2_CONTROLLER_CONFIG_DISABLE_PORT1_CLOCK = 16,
    PS2_CONTROLLER_CONFIG_DISABLE_PORT2_CLOCK = 32,
    PS2_CONTROLLER_CONFIG_ENABLE_PORT1_TRANSLATION = 64, // enabled = data is translated into scan code set 1
};
enum ps2_controller_output_port {
    PS2_CONTROLLER_OUTPUTP_DONT_SYSTEM_RESET = 1, // NEEDS TO BE SET, otherwise computer lockup
    PS2_CONTROLLER_OUTPUTP_A20_GATE = 2,
    PS2_CONTROLLER_OUTPUTP_PORT2_CLOCK = 4,
    PS2_CONTROLLER_OUTPUTP_PORT2_DATA = 8,
    PS2_CONTROLLER_OUTPUTP_OUT_BUF_FULL_PORT1 = 16, // output buffer (1 byte) for port 1 is full
    PS2_CONTROLLER_OUTPUTP_OUT_BUF_FULL_PORT2 = 32,
    PS2_CONTROLLER_OUTPUTP_PORT1_CLOCK = 64,
    PS2_CONTROLLER_OUTPUTP_PORT1_DATA = 128,
};
enum ps2_controller_commands {
    PS2_CONTROLLER_COMMAND_READ_BYTE = 0x20, // this + address&0x1F, 0 is to get the controller config byte
    PS2_CONTROLLER_COMMAND_WRITE_BYTE = 0x60, // make sure status register bit 1 is clear (if not, needs to be read from 0x60), send next byte to DATA_PORT
    PS2_CONTROLLER_COMMAND_DISABLE_PORT2 = 0xA7,
    PS2_CONTROLLER_COMMAND_ENABLE_PORT2 = 0xA8,
    PS2_CONTROLLER_COMMAND_TEST_PORT2 = 0xA9, // responds with PS2_CONTROLLER_TEST_*
    PS2_CONTROLLER_COMMAND_SELF_TEST = 0xAA, // responds with PS_CONTROLLER_SELF_TEST_*
    PS2_CONTROLLER_COMMAND_TEST_PORT1 = 0xAB, // // responds with PS2_CONTROLLER_TEST_*
    PS2_CONTROLLER_COMMAND_DIAG_READ_ALL = 0xAC,
    PS2_CONTROLLER_COMMAND_DISABLE_PORT1 = 0xAD,
    PS2_CONTROLLER_COMMAND_ENABLE_PORT1 = 0xAE,
    PS2_CONTROLLER_COMMAND_READ_INPUT_PORT = 0xC0, // unstandardised output!
    PS2_CONTROLLER_COMMAND_COPY_INPUT0_3_STATUS4_7 = 0xC1, // copy bits 0-3 of input port to status 4-7
    PS2_CONTROLLER_COMMAND_COPY_INPUT4_7_STATUS4_7 = 0xC2, // copy bits 4-7 of input port to status 4-7
    PS2_CONTROLLER_COMMAND_READ_OUTPUT_PORT = 0xD0, // responds with output port
    PS2_CONTROLLER_COMMAND_WRITE_OUTPUT_PORT = 0xD1, // see PS2_CONTROLLER_COMMAND_WRITE_BYTE
    PS2_CONTROLLER_COMMAND_WRITE_PORT1_OUT_BUF = 0xD2,
    PS2_CONTROLLER_COMMAND_WRITE_PORT2_OUT_BUF = 0xD3,
    PS2_CONTROLLER_COMMAND_WRITE_PORT2_IN_BUF = 0xD4, // allows to send stuff to port 2

    // 0xF0 to 0xFF "Pulse output line low for 6 ms. Bits 0 to 3 are used as a mask (0 = pulse line, 1 = don't pulse line) and correspond to 4 different output lines."
};

enum ps2_keyboard_scan_code_sets {
    PS2_SCAN_CODE_GET_CURRENT,
    PS2_SCAN_CODE_SET_1,
    PS2_SCAN_CODE_SET_2,
    PS2_SCAN_CODE_SET_3
};

enum ps2_scan_code_sets_res {
    PS2_SCAN_CODE_SET_TRANSLATED_1 = 0x43,
    PS2_SCAN_CODE_SET_TRANSLATED_2 = 0x41,
    PS2_SCAN_CODE_SET_TRANSLATED_3 = 0x3f,
};
enum ps2_keyboard_commands {
    PS2_COMMAND_SET_LED = 0xED, // send 1 extra byte
    PS2_COMMAND_ECHO, // keyboard replies ECHO
    PS2_COMMAND_SCAN_CODE = 0xF0, // get/set scan code set, read 1 extra byte if get 
    PS2_COMMAND_ID_KEYBOARD = 0xF2, // very complicated, basically 0 - 2 bytes depending on device and with needed timeouts
    PS2_COMMAND_SET_TYPEMATIC, // repeat rate, delay before repeat, 1 extra byte, 0-4 = repeat (0 = 30hz, 31 = 2hz), 5-6 = delay (250 + 250*value), 7 = 0
    PS2_COMMAND_ENABLE_SCANNING, // keyboard will send inputs, to not interrupt reading
    PS2_COMMAND_DISABLE_SCANNING,
    PS2_COMMAND_SET_DEFAULTS,
    
    PS2_COMMAND_SC3_SET_ALL_TYPEMATIC,
    PS2_COMMAND_SC3_SET_ALL_PRESS_RELEASE,
    PS2_COMMAND_SC3_SET_ALL_PRESS_ONLY,
    PS2_COMMAND_SC3_SET_ALL_TPR, // press, release, autorepeat
    PS2_COMMAND_SC3_SET_SPEC_TYPEMATIC, // send 1 byte - scancode
    PS2_COMMAND_SC3_SET_SPEC_PRESS_RELEASE,
    PS2_COMMAND_SC3_SET_SPEC_PRESS_ONLY,
    
    PS2_COMMAND_RESEND_LAST_BYTE, // failed to read for example
    PS2_COMMAND_RESET_SELF_TEST,
};

enum ps2_controller_status_register {
    PS2_STATUS_OUTPUT_BUFFER_FULL = 1, // set before reading from 0x60
    PS2_STATUS_INPUT_BUFFER_FULL = 2, // unset before writing
    PS2_STATUS_PASSED_POST = 4, // see PS2_CONTROLLER_CONFIG_PASED_POST
    PS2_STATUS_DATA_INPUT_IS_FOR_CTRL = 8,
    PS2_STATUS_TIMED_OUT_ERROR = 64,
    PS2_STATUS_PARITY_ERROR = 128,
};
enum ps2_responses {
    PS2_RESPONSE_ERROR,
    PS2_RESPONSE_SELF_TEST_PASSED = 0xAA,
    PS2_RESPONSE_ECHO = 0xEE,
    PS2_RESPONSE_ACK = 0xFA,
    PS2_RESPONSE_SELF_TEST_FAILED = 0xFC,
    PS2_RESPONSE_SELF_TEST_FAILED_ALT = 0xFD,
    PS2_RESPONSE_RESEND_LAST_BYTE = 0xFE,
    PS2_RESPONSE_ERROR_ALT = 0xFF
};

enum ps2_command_set_led_byte {
    PS2_LED_SCROLLLOCK = 1,
    PS2_LED_NUMBERLOCK = 2,
    PS2_LED_CAPSLOCK = 3,
};

#define PS2_2_BYTE_K_CODE 0xE0
#define PS2_3_BYTE_K_CODE 0xE1 // only pause (E1 1D 45 E1 9D C5), which sends its press and then immediately release, hence it doesn't have a full-fledged pause
#define PS2_SC1_3B_PAUSE_1 0x1D
#define PS2_SC1_3B_PAUSE_2 0x45
#define PS2_SC2_3B_PAUSE_1 0x1D
#define PS2_SC2_3B_PAUSE_2 0x45
#define PS2_SC1_KEY_RELEASED_MASK KEY_RELEASED_MASK
#define PS2_SC2_KEY_RELEASE_BYTE 0xF0

enum ps2_keycodes_set_2 {
    PS2_SC2_KEY_F9 = 0x01,
    PS2_SC2_KEY_F5 = 0x03,
    PS2_SC2_KEY_F3,
    PS2_SC2_KEY_F1,
    PS2_SC2_KEY_F2,
    PS2_SC2_KEY_F12,
    PS2_SC2_KEY_F10 = 0x09,
    PS2_SC2_KEY_F8,
    PS2_SC2_KEY_F6,
    PS2_SC2_KEY_F4,
    PS2_SC2_KEY_TAB,
    PS2_SC2_KEY_BACKTICK,
    PS2_SC2_KEY_LALT = 0x11,
    PS2_SC2_KEY_LSHIFT,
    PS2_SC2_KEY_LCONTROL = 0x14,
    PS2_SC2_KEY_Q,
    PS2_SC2_KEY_1,
    PS2_SC2_KEY_Z = 0x1A,
    PS2_SC2_KEY_S,
    PS2_SC2_KEY_A,
    PS2_SC2_KEY_W,
    PS2_SC2_KEY_2,
    PS2_SC2_KEY_C = 0x21,
    PS2_SC2_KEY_X,
    PS2_SC2_KEY_D,
    PS2_SC2_KEY_E,
    PS2_SC2_KEY_4,
    PS2_SC2_KEY_3,
    PS2_SC2_KEY_SPACE = 0x29,
    PS2_SC2_KEY_V,
    PS2_SC2_KEY_F,
    PS2_SC2_KEY_T,
    PS2_SC2_KEY_R,
    PS2_SC2_KEY_5,
    PS2_SC2_KEY_N = 0x31,
    PS2_SC2_KEY_B,
    PS2_SC2_KEY_H,
    PS2_SC2_KEY_G,
    PS2_SC2_KEY_Y,
    PS2_SC2_KEY_6,
    PS2_SC2_KEY_M = 0x3A,
    PS2_SC2_KEY_J,
    PS2_SC2_KEY_U,
    PS2_SC2_KEY_7,
    PS2_SC2_KEY_8,
    PS2_SC2_KEY_COMMA = 0x41,
    PS2_SC2_KEY_K,
    PS2_SC2_KEY_I,
    PS2_SC2_KEY_O,
    PS2_SC2_KEY_0,
    PS2_SC2_KEY_9,
    PS2_SC2_KEY_DOT = 0x49,
    PS2_SC2_KEY_SLASH,
    PS2_SC2_KEY_L,
    PS2_SC2_KEY_SEMICOLON,
    PS2_SC2_KEY_P,
    PS2_SC2_KEY_MINUS,
    PS2_SC2_KEY_APOSTROPHE = 0x52,
    PS2_SC2_KEY_LBRACE = 0x54,
    PS2_SC2_KEY_EQUAL,
    PS2_SC2_KEY_CAPSLOCK = 0x58,
    PS2_SC2_KEY_RSHIFT,
    PS2_SC2_KEY_ENTER,
    PS2_SC2_KEY_RBRACE,
    PS2_SC2_KEY_BACKSLASH = 0x5D,
    PS2_SC2_KEY_BACKSPACE = 0x66,
    PS2_SC2_KEY_KP_1 = 0x69,
    PS2_SC2_KEY_KP_4 = 0x6B,
    PS2_SC2_KEY_KP_7,
    PS2_SC2_KEY_KP_0 = 0x70,
    PS2_SC2_KEY_KP_DOT,
    PS2_SC2_KEY_KP_2,
    PS2_SC2_KEY_KP_5,
    PS2_SC2_KEY_KP_6,
    PS2_SC2_KEY_KP_8,
    PS2_SC2_KEY_ESCAPE,
    PS2_SC2_KEY_NUMLOCK,
    PS2_SC2_KEY_F11,
    PS2_SC2_KEY_KP_PLUS,
    PS2_SC2_KEY_KP_3,
    PS2_SC2_KEY_KP_MINUS,
    PS2_SC2_KEY_KP_ASTERISK,
    PS2_SC2_KEY_KP_9,
    PS2_SC2_KEY_SCROLLLOCK,
    PS2_SC2_KEY_F7 = 0x83,
};


enum ps2_keycodes_set_1_second_byte { // refer to keyboard_scan_set_1 for the 1 byte codes
    PS2_SC1_B2_KEY_MULTIMEDIA_PREV_TRACK = 0x10,
    PS2_SC1_B2_KEY_MULTIMEDIA_NEXT_TRACK = 0x19,
    PS2_SC1_B2_KEY_KP_ENTER = 0x1C,
    PS2_SC1_B2_KEY_RCONTROL,
    PS2_SC1_B2_KEY_MULTIMEDIA_MUTE = 0x20,
    PS2_SC1_B2_KEY_MULTIMEDIA_CALCULATOR,
    PS2_SC1_B2_KEY_MULTIMEDIA_PLAY,
    PS2_SC1_B2_KEY_MULTIMEDIA_STOP = 0x24,

    PS2_SC1_B2_FAKE_LSHIFT = 0x2A, // a "grey" left shift, used for backwards compatibility with AT keyboards on certain keys
    PS2_SC1_B2_KEY_PRINT_SCREEN = 0x37, // ctrl+print screen technically

    PS2_SC1_B2_FAKE_SCROLLOCK = 0x46, // break (ctrl+pause) sends this for backwards compatibility
    PS2_SC1_B2_KEY_BREAK = 0xc6,

    PS2_SC1_B2_KEY_MULTIMEDIA_VOLUME_DOWN = 0x2E,
    PS2_SC1_B2_KEY_MULTIMEDIA_VOLUME_UP = 0x30,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_HOME = 0x32,
    PS2_SC1_B2_KEY_KP_SLASH = 0x35,

    PS2_SC1_B2_KEY_RALT = 0x38, // altgr

    PS2_SC1_B2_KEY_HOME = 0x47,
    PS2_SC1_B2_KEY_UP,
    PS2_SC1_B2_KEY_PAGE_UP,
    PS2_SC1_B2_KEY_LEFT = 0x4B,
    PS2_SC1_B2_KEY_RIGHT = 0x4D,
    PS2_SC1_B2_KEY_END = 0x4F,
    PS2_SC1_B2_KEY_DOWN,
    PS2_SC1_B2_KEY_PAGE_DOWN,
    PS2_SC1_B2_KEY_INSERT,
    PS2_SC1_B2_KEY_DELETE,
    PS2_SC1_B2_KEY_LMETA = 0x5B, // the super key
    PS2_SC1_B2_KEY_RMETA,
    PS2_SC1_B2_KEY_COMPOSE, // the wierd menu key that does right click, also called the apps key
    PS2_SC1_B2_KEY_ACPI_POWER,
    PS2_SC1_B2_KEY_ACPI_SLEEP,
    PS2_SC1_B2_KEY_ACPI_WAKE = 0x63,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_SEARCH = 0x65,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_FAVORITES,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_REFRESH,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_STOP,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_FORWARD,
    PS2_SC1_B2_KEY_MULTIMEDIA_WWW_BACK,
    PS2_SC1_B2_KEY_MULTIMEDIA_MY_COMPUTER,
    PS2_SC1_B2_KEY_MULTIMEDIA_EMAIL,
    PS2_SC1_B2_KEY_MULTIMEDIA_MEDIA_SELECT,
};


enum ps2_keyboard_set_2_second_byte {
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_SEARCH = 0x10,
    PS2_SC2_B2_KEY_RALT,
    PS2_SC2_B2_KEY_RCONTROL = 0x14,
    PS2_SC2_B2_KEY_MULTIMEDIA_PREV_TRACK,
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_FAVORITES = 0x18,
    PS2_SC2_B2_KEY_LMETA = 0x1F,
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_REFRESH = 0x20,
    PS2_SC2_B2_KEY_MULTIMEDIA_VOLUME_DOWN,
    PS2_SC2_B2_KEY_MULTIMEDIA_MUTE = 0x23,
    PS2_SC2_B2_KEY_RMETA = 0x27,
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_STOP = 0x28,
    PS2_SC2_B2_KEY_MULTIMEDIA_CALCULATOR = 0x2B,
    PS2_SC2_B2_KEY_COMPOSE = 0x2F,
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_FORWARD,
    PS2_SC2_B2_KEY_MULTIMEDIA_VOLUME_UP = 0x32,
    PS2_SC2_B2_KEY_MULTIMEDIA_PLAY = 0x34,
    PS2_SC2_B2_KEY_ACPI_POWER = 0x37,
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_BACK,
    PS2_SC2_B2_KEY_MULTIMEDIA_WWW_HOME = 0x3A,
    PS2_SC2_B2_KEY_MULTIMEDIA_STOP,
    PS2_SC2_B2_KEY_ACPI_SLEEP = 0x3F,
    PS2_SC2_B2_KEY_MULTIMEDIA_MY_COMPUTER,
    PS2_SC2_B2_KEY_MULTIMEDIA_EMAIL = 0x48,
    PS2_SC2_B2_KEY_KP_SLASH = 0x4A,
    PS2_SC2_B2_KEY_MULTIMEDIA_NEXT_TRACK = 0x4D,
    PS2_SC2_B2_KEY_MULTIMEDIA_MEDIA_SELECT = 0x50,
    PS2_SC2_B2_KEY_KP_ENTER = 0x5A,
    PS2_SC2_B2_KEY_ACPI_WAKE = 0x5E,
    PS2_SC2_B2_KEY_END = 0x69,
    PS2_SC2_B2_KEY_LEFT = 0x6B,
    PS2_SC2_B2_KEY_HOME,
    PS2_SC2_B2_KEY_INSERT = 0x70,
    PS2_SC2_B2_KEY_DELETE,
    PS2_SC2_B2_KEY_DOWN,
    PS2_SC2_B2_KEY_RIGHT = 0x74,
    PS2_SC2_B2_KEY_UP,
    PS2_SC2_B2_KEY_PAGE_DOWN = 0x7A,
    PS2_SC2_B2_KEY_PAGE_UP = 0x7D,
};

void keyboard_init();
void keyboard_driver(char device_num);

#endif